### ISSUE TITLE
Shift remains active when I have Shift key cancelling Caps

### ISSUE THREAD

**Issue by alexandrupetrini** [nathanielsimard/overview-navigation#20] opened 2020-02-08 19:57 UTC
Hi,

I am usually activating "Shift cancels Caps Lock" keyboard option and when I am in overview, pressing Shift key activates window closing mode. I can only deactivate it when I press both Shift keys together. Is there something you can do about it?

![image](https://user-images.githubusercontent.com/44755709/74091170-6317cd00-4abd-11ea-82bb-8cce14ce04ef.png)

![Screenshot from 2020-02-08 21-56-31](https://user-images.githubusercontent.com/44755709/74091236-f94bf300-4abd-11ea-8a4f-6e01e63b48d2.png)

**Comment by nathanielsimard** [comment] 2020-02-09 01:04
At the moment, the closing indicators are just visual, they do not influence if the windows are going to be closed. Only capital letters can close windows.

Can you confirm that the behavior is correct and the issue is only visual ?

I think it can be fixed, the caplock state should influence the current function and should be available with the Gnome Api. Most of the work is to find it in the doc 😅. 

Here's the current function I'm talking about, very very simple.

```javascript
  isTooltipsClosingKeySymbol (keySymbol) {
    return keySymbol === this.keys.KEY_Shift_L || keySymbol === this.keys.KEY_Shift_R
  }
```

**Comment by nathanielsimard** [comment] 2020-02-09 02:45
I was wrong, I've check and its depends on the visual tool tip and not on the case.

**Comment by nathanielsimard** [comment] 2020-02-09 21:02
I made the fix! Can you please test it to make sure it works on your system and that it is the expected behavior.

You can try the PR #22  by running the following command then restarting the shell (`Alt-f2 -> r` on X11 or log out / in on Wayland).

```sh
npm install
npm run local:install 
```

Thanks

**Comment by alexandrupetrini** [comment] 2020-02-13 18:50
Hi there, I've been testing it the last 2

**Closed** 2020-02-14 04:57 UTC
